### PR TITLE
Update Salada.podspec

### PR DESCRIPTION
**Pull request by Saik0s**
Here is a .podspec file for your library. Unfortunately, there is no beautiful solution currently, hope this solution will work for you. I checked this .podspec using `pod lib lint` command and it passed validation.

Good luck!

### CODE REVIEW

**Comment by 1amageek** [comment]
Wow! so cool.
Thank you for PR😁

**Comment by 1amageek** [comment]
Please change branch's target to `develop`.

**Comment by 1amageek** [comment]
With your wonderful PR, Salada supported to Cocoapods. very very thank you.

**Comment by Saik0s** [comment]
I am glad to help!

**Pull request merged**
